site_name: Powdered World Engine

site_url: https://cannedbottle.github.io/powderedworld-docs/

repo_url: https://github.com/CannedBottle/powdered_world_engine


theme:
  name: material

  favicon: img/PowderedWorldIcon.png
  logo: img/PowderedWorldIcon-black.png

  palette:
    scheme: slate

    primary: amber
    accent: light blue


nav:
  - Navigation Home: index.md
  - Getting Started: getting_started.md
  - Reference:
      - PowderSimulation Node: powdersimnode.md
      - SandInfoCS Autoload: sandinfocs.md
  - About: about.md
